#!/bin/bash
# Shest should fail if a project has not been set up.

. "$SHEST_SCRIPT" "--doNothing"

testingShest

"$SHEST_SCRIPT" ## Test this.

expect_exitCode 1
expect_errorContains 'It looks like shest has not been initialised'
