#!/bin/bash
# Create a project.

. "$SHEST_SCRIPT" "--doNothing"

"$SHEST_SCRIPT" --createProject ## Test this.

expect_exitCode 0
expect_exists "shest/unit/myFirstStage/exampleTest" "A dummy test in a stage should be created."
expect_exists "shest/config/general" "Default config should be created."
expect_resultContains "Excellent."
