#!/bin/bash
# Fix the broken test. And run the test again. It should succeed.

. "$SHEST_SCRIPT" "--doNothing"

beginNestedShest

# Do the fix.
sed -i 's#doSomething#true#g; s#^if.*then#if [ "$exitCode" == 0 ]; then#g' shest/unit/myFirstStage/exampleTest

# Do the work.
$SHEST_SCRIPT ## Test this.

endNestedShest

expect_exitCode 0
